"""reports and audit trail

Revision ID: 7584abdbe5df
Revises: 
Create Date: 2026-08-06 02:17:37.974087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7584abdbe5df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_audit',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('report_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('report_audit_owner_idx', 'report_audit', ['owner_id', sa.literal_column('performed_at DESC')], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('reports_fts_idx', 'reports', [sa.literal_column("to_tsvector('english', title || ' ' || body)")], unique=False, postgresql_using='gin')
    op.create_index('reports_owner_live_idx', 'reports', ['owner_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('reports_owner_live_idx', table_name='reports', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('reports_fts_idx', table_name='reports', postgresql_using='gin')
    op.drop_table('reports')
    op.drop_index('report_audit_owner_idx', table_name='report_audit')
    op.drop_table('report_audit')
    # ### end Alembic commands ###
