"""turn traces and node events

Revision ID: 9a1c4b2e77d1
Revises: 7584abdbe5df
Create Date: 2026-08-06

Written by hand rather than autogenerated: the database was not running at the
time, and autogenerate output needs adjusting for server defaults anyway.
`test_migrations_match_the_models` (db-marked) is what proves it matches
`models.py`.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9a1c4b2e77d1"
down_revision: Union[str, Sequence[str], None] = "7584abdbe5df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "traces",
        sa.Column("turn_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("answer", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("redactions", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "bytes_billed", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "attempts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("turn_id"),
    )
    op.create_index("traces_recent_idx", "traces", ["owner_id", "created_at"])
    op.create_index("traces_session_idx", "traces", ["session_id", "created_at"])

    op.create_table(
        "turn_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("turn_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("turn_events_turn_idx", "turn_events", ["turn_id", "seq"])
    op.create_index("turn_events_node_idx", "turn_events", ["node"])


def downgrade() -> None:
    op.drop_index("turn_events_node_idx", table_name="turn_events")
    op.drop_index("turn_events_turn_idx", table_name="turn_events")
    op.drop_table("turn_events")
    op.drop_index("traces_session_idx", table_name="traces")
    op.drop_index("traces_recent_idx", table_name="traces")
    op.drop_table("traces")
